Form styling
codeyoungstown/next-codeyoungstown.com pull request #17
Opened 2022-07-10 13:42 UTC by ryanlalchand

2022-07-10 22:59 UTC, JoeDuncko commented
Note that this diff seems to include diffs that is in another PR. That might cause some issues with squash and merge.

2022-07-10 23:03 UTC, JoeDuncko requested changes
Good start! Check out the comments

2022-07-10 23:03 UTC, JoeDuncko commented on pages/jobs-form.tsx
> +          <br />
`<br>`s are not a great way to add spacing. Use styles instead.

2022-07-10 23:03 UTC, JoeDuncko commented on pages/jobs-form.tsx
> +            className="bg-CYgray
Might want to create a `FormField` component that abstracts some of props.

2022-07-10 23:03 UTC, JoeDuncko commented on pages/jobs-form.tsx
> +          <label htmlFor="email">Your Email: &nbsp;</label> <br />
`&nbsp;` is not a great way to add spacing, use styles instead.

2022-07-10 23:03 UTC, JoeDuncko commented on pages/jobs.tsx
> +        <a className="hover:text-gray-300">Add a job listing</a>
Maybe "Submit a Job"?

2022-07-15 19:49 UTC, garrett-huggins approved these changes

2022-07-15 19:49 UTC, JoeDuncko approved these changes

2022-07-15 19:50 UTC, merged