Add Https to mailto to avoid form insecure message
codeyoungstown/next-codeyoungstown.com pull request #19
Opened 2022-07-10 17:54 UTC by ryanlalchand

2022-07-10 23:06 UTC, JoeDuncko requested changes
Note that this PR includes changes that are in other PRs, so it's kinda hard to tell what was supposed to be in just this one.

Note comments

2022-07-10 23:06 UTC, JoeDuncko commented on pages/jobs-form.tsx
> +        action="https://mailto:contact@codeyoungstown.com?subject=New Job Listing"
Does that actually work like that? I have no idea

2022-07-10 23:06 UTC, JoeDuncko commented on pages/jobs-form.tsx
> +        action="https://mailto:contact@codeyoungstown.com?subject=New Job Listing"
After doing some googling, I can't find a source that says to add `https://` to mailto links. Do you have something you were referencing?

2022-07-13 22:55 UTC, ryanlalchand commented on pages/jobs-form.tsx
> +        action="https://mailto:contact@codeyoungstown.com?subject=New Job Listing"
Just some Stack Overflow post as a hail mary. When I pushed this, the Vercel hosted version didn't display the Autofill Danger error

2022-07-15 19:53 UTC, JoeDuncko approved these changes

2022-07-15 19:53 UTC, merged